version: '3.8'

services:
  # MongoDB 数据库服务
  mongodb:
    image: registry.cn-hangzhou.aliyuncs.com/misaka-images/mongo:6.0.2
    container_name: naive-service-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: topaz
      MONGO_INITDB_ROOT_PASSWORD: ipcMasterTopazzz
      MONGO_INITDB_DATABASE: StarPeaceCompany
    volumes:
      - mongo-data:/data/db
      - ./mongodb-logs:/var/log/mongodb
    command: ["mongod", "--logpath", "/var/log/mongodb/mongod.log", "--logappend"]

  # 应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: naive-service-app
    restart: unless-stopped
    ports:
      - "9090:9090"
    environment:
      NODE_ENV: production
      PORT: 9090
      # MongoDB 连接配置
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_NAME: StarPeaceCompany
      DB_USER: topaz
      DB_PASSWORD: ipcMasterTopazzz
    volumes:
      - ./logs:/usr/src/app/logs
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9090/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx 反向代理 (可选)
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/misaka-images/nginx:alpine
    container_name: naive-service-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app
    profiles:
      - with-nginx  # 使用 --profile with-nginx 来启用

volumes:
  mongo-data:
    driver: local 